using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DAL;
using BUS;
using DevExpress.XtraExport;
using DevExpress.XtraEditors;
using System.Data.Linq;


namespace PhanMemQuanLyThuVien
{
    public partial class USListSach : UserControl
    {
        public USListSach()
        {
            InitializeComponent(); 
            this.Dock = DockStyle.Fill;
            HienThi();
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = new DAL.ThuVienDataContext().SACHes;
        }

        //public void HienThiDanhSachSach()
        //{
        //    BUSSach busSach = new BUSSach();
        //    gridView1.DataSource = busSach.LayToanBoSach();
        //}

        public void HienThi()
        {
            gridControl1.MainView = layoutView1;
        }
    }
}
